import { useCallback, useEffect, useRef, useState } from 'react';

interface UseGeminiVoiceOptions {
    /** Short-lived Gemini Live API token generated by the backend */
    token: string | null;
    /** Model to use */
    model?: string;
    /** System instruction for the AI */
    systemInstruction?: string;
    /** Voice name for responses */
    voiceName?: string;
    /** Language code */
    language?: string;
    /** Callback when AI response audio starts */
    onSpeakingStart?: () => void;
    /** Callback when AI response audio ends */
    onSpeakingEnd?: () => void;
    /** Callback when transcript is received */
    onTranscript?: (text: string, isFinal: boolean) => void;
    /** Callback when AI responds with text */
    onResponseText?: (text: string) => void;
    /** Callback for audio intensity (0-1) */
    onAudioIntensity?: (intensity: number) => void;
}

interface UseGeminiVoiceReturn {
    /** Whether the session is active */
    isConnected: boolean;
    /** Whether the AI is currently speaking */
    isSpeaking: boolean;
    /** Whether we are listening to user input */
    isListening: boolean;
    /** Whether the AI is processing/thinking */
    isProcessing: boolean;
    /** Current audio intensity (0-1) from microphone (Reactive) */
    audioIntensity: number;
    /** Function to get raw audio intensity instantly without re-rendering */
    getAudioVolume: () => number;
    /** Last transcript from user */
    transcript: string;
    /** Last response from AI */
    lastResponse: string;
    /** Start the voice session */
    startSession: (override?: { token?: string; model?: string; voiceName?: string }) => Promise<void>;
    /** End the voice session */
    endSession: () => void;
    /** Toggle listening on/off */
    toggleListening: () => void;
    /** Send a text message instead of voice */
    sendTextMessage: (text: string) => void;
    /** Any error that occurred */
    error: string | null;
}

type LiveMessage = {
    setupComplete?: boolean;
    toolCall?: {
        functionCalls?: Array<{
            id?: string;
            name: string;
            args?: unknown;
        }>;
    };
    serverContent?: {
        inputTranscription?: { text?: string; finished?: boolean };
        outputTranscription?: { text?: string };
        modelTurn?: {
            parts?: Array<{
                text?: string;
                inlineData?: {
                    mimeType?: string;
                    data: string;
                };
            }>;
        };
        interrupted?: boolean;
        turnComplete?: boolean;
    };
    error?: {
        message?: string;
        status?: string;
        code?: number;
    };
};

const AUDIO_WORKLET_CODE = `
class AudioProcessor extends AudioWorkletProcessor {
    constructor() {
        super();
        this.bufferSize = 4096;
        this.buffer = new Float32Array(this.bufferSize);
        this.bufferIndex = 0;
    }

    process(inputs, outputs, parameters) {
        const input = inputs[0];
        if (input.length > 0) {
            const channelData = input[0];
            for (let i = 0; i < channelData.length; i++) {
                this.buffer[this.bufferIndex++] = channelData[i];
                if (this.bufferIndex >= this.bufferSize) {
                    const pcm16 = new Int16Array(this.bufferSize);
                    for (let j = 0; j < this.bufferSize; j++) {
                        pcm16[j] = Math.max(-32768, Math.min(32767, Math.floor(this.buffer[j] * 32768)));
                    }
                    this.port.postMessage({ type: 'audio', data: pcm16.buffer });
                    this.bufferIndex = 0;
                }
            }

            let sum = 0;
            for (let i = 0; i < channelData.length; i++) {
                sum += Math.abs(channelData[i]);
            }
            const intensity = Math.min(1, (sum / channelData.length) * 10);
            this.port.postMessage({ type: 'intensity', value: intensity });
        }
        return true;
    }
}
registerProcessor('audio-processor', AudioProcessor);
`;

const DEFAULT_MODEL = 'gemini-3.1-flash-live-preview';
const DEFAULT_VOICE = 'Kore';

const toFriendlyVoiceError = (message?: string) => {
    const raw = message || '';
    if (
        raw.includes('<!DOCTYPE') ||
        raw.includes('Unexpected token') ||
        raw.includes('not valid JSON') ||
        raw.includes('BidiGenerateContent') ||
        raw.includes('401') ||
        raw.includes('403')
    ) {
        return 'A credencial temporaria de voz nao foi aceita pelo Live API. Gere uma nova sessao e tente novamente.';
    }
    if (raw.includes('Permission') || raw.includes('denied') || raw.includes('NotAllowedError')) {
        return 'Permissao de microfone bloqueada. Libere o microfone no navegador e tente novamente.';
    }
    if (raw.includes('Token') || raw.includes('token')) {
        return 'Token de voz indisponivel. Tente iniciar a voz novamente.';
    }
    return raw || 'Nao foi possivel iniciar o modo voz.';
};

const uint8ToBase64 = (bytes: Uint8Array) => {
    let binary = '';
    const chunkSize = 0x8000;
    for (let index = 0; index < bytes.length; index += chunkSize) {
        const chunk = bytes.subarray(index, index + chunkSize);
        binary += String.fromCharCode(...chunk);
    }
    return btoa(binary);
};

const parseLiveMessage = (raw: unknown): LiveMessage => {
    if (typeof raw !== 'string') {
        throw new Error('Evento de voz em formato inesperado.');
    }

    const trimmed = raw.trim();
    if (!trimmed) {
        throw new Error('Evento de voz vazio.');
    }

    if (trimmed.startsWith('<')) {
        throw new Error('Resposta HTML recebida do Live API.');
    }

    return JSON.parse(trimmed) as LiveMessage;
};

export function useGeminiVoice({
    token,
    model = DEFAULT_MODEL,
    systemInstruction = 'Voce e o Synapse AI, um assistente de voz inteligente e empatico. Responda de forma conversacional, natural e concisa em portugues brasileiro. Seja prestativo e amigavel.',
    voiceName = DEFAULT_VOICE,
    language: _language = 'pt-BR',
    onSpeakingStart,
    onSpeakingEnd,
    onTranscript: _onTranscript,
    onResponseText,
    onAudioIntensity,
}: UseGeminiVoiceOptions): UseGeminiVoiceReturn {
    const [isConnected, setIsConnected] = useState(false);
    const [isSpeaking, setIsSpeaking] = useState(false);
    const [isListening, setIsListening] = useState(false);
    const [isProcessing, setIsProcessing] = useState(false);
    const [audioIntensity, setAudioIntensity] = useState(0);
    const audioIntensityRef = useRef(0);
    const lastIntensityUpdateRef = useRef(0);
    const [transcript, _setTranscript] = useState('');
    const [lastResponse, setLastResponse] = useState('');
    const [error, setError] = useState<string | null>(null);

    const wsRef = useRef<WebSocket | null>(null);
    const audioContextRef = useRef<AudioContext | null>(null);
    const streamRef = useRef<MediaStream | null>(null);
    const workletNodeRef = useRef<AudioWorkletNode | null>(null);
    const silenceNodeRef = useRef<GainNode | null>(null);
    const activeAudioSourcesRef = useRef<AudioBufferSourceNode[]>([]);
    const nextPlayTimeRef = useRef(0);
    const isListeningRef = useRef(false);
    const setupCompleteRef = useRef(false);
    const manualCloseRef = useRef(false);

    const stopAudioPlayback = useCallback(() => {
        activeAudioSourcesRef.current.forEach((source) => {
            try {
                source.stop();
            } catch {
                // Source may already be stopped.
            }
        });
        activeAudioSourcesRef.current = [];
        nextPlayTimeRef.current = 0;
        setIsSpeaking(false);
        onSpeakingEnd?.();
    }, [onSpeakingEnd]);

    const cleanupResources = useCallback(() => {
        stopAudioPlayback();

        if (workletNodeRef.current) {
            workletNodeRef.current.disconnect();
            workletNodeRef.current = null;
        }

        if (silenceNodeRef.current) {
            silenceNodeRef.current.disconnect();
            silenceNodeRef.current = null;
        }

        if (streamRef.current) {
            streamRef.current.getTracks().forEach((track) => track.stop());
            streamRef.current = null;
        }

        if (audioContextRef.current) {
            const context = audioContextRef.current;
            audioContextRef.current = null;
            void context.close().catch(() => undefined);
        }

        setIsConnected(false);
        setIsListening(false);
        setIsSpeaking(false);
        setIsProcessing(false);
        setAudioIntensity(0);
        audioIntensityRef.current = 0;
        isListeningRef.current = false;
        setupCompleteRef.current = false;
    }, [stopAudioPlayback]);

    const playPcmAudio = useCallback((base64Audio: string) => {
        const audioContext = audioContextRef.current;
        if (!audioContext) return;

        const binary = atob(base64Audio);
        const bytes = new Uint8Array(binary.length);
        for (let index = 0; index < binary.length; index += 1) {
            bytes[index] = binary.charCodeAt(index);
        }

        const samples = new Int16Array(bytes.buffer);
        const floatSamples = new Float32Array(samples.length);
        for (let index = 0; index < samples.length; index += 1) {
            floatSamples[index] = samples[index] / 32768;
        }

        const audioBuffer = audioContext.createBuffer(1, floatSamples.length, 24000);
        audioBuffer.getChannelData(0).set(floatSamples);

        const source = audioContext.createBufferSource();
        source.buffer = audioBuffer;
        source.connect(audioContext.destination);

        const currentTime = audioContext.currentTime;
        if (nextPlayTimeRef.current < currentTime) {
            nextPlayTimeRef.current = currentTime;
        }

        if (activeAudioSourcesRef.current.length === 0) {
            setIsSpeaking(true);
            onSpeakingStart?.();
        }

        source.start(nextPlayTimeRef.current);
        nextPlayTimeRef.current += audioBuffer.duration;
        activeAudioSourcesRef.current.push(source);

        source.onended = () => {
            activeAudioSourcesRef.current = activeAudioSourcesRef.current.filter((item) => item !== source);
            if (activeAudioSourcesRef.current.length === 0) {
                setIsSpeaking(false);
                onSpeakingEnd?.();
            }
        };
    }, [onSpeakingEnd, onSpeakingStart]);

    const handleParsedMessage = useCallback((data: LiveMessage) => {
        if (data.error) {
            setError(toFriendlyVoiceError(data.error.message || data.error.status));
            setIsProcessing(false);
            return;
        }

        if (data.setupComplete) {
            setupCompleteRef.current = true;
            setIsConnected(true);
            setIsListening(true);
            setIsProcessing(false);
            isListeningRef.current = true;
            return;
        }

        const content = data.serverContent;
        if (!content) return;

        if (content.inputTranscription?.text) {
            if (content.inputTranscription.finished) {
                _setTranscript((previous) => `${previous} ${content.inputTranscription?.text || ''}`.trim());
            }
            _onTranscript?.(content.inputTranscription.text, Boolean(content.inputTranscription.finished));
        }

        if (content.outputTranscription?.text) {
            setLastResponse((previous) => `${previous}${content.outputTranscription?.text || ''}`);
            onResponseText?.(content.outputTranscription.text);
        }

        if (content.modelTurn) {
            const parts = content.modelTurn.parts || [];
            for (const part of parts) {
                if (part.text) {
                    setLastResponse((previous) => previous + part.text);
                    onResponseText?.(part.text);
                }
                if (part.inlineData?.mimeType?.startsWith('audio/')) {
                    playPcmAudio(part.inlineData.data);
                }
            }
        }

        if (content.interrupted) {
            stopAudioPlayback();
        }

        if (content.turnComplete) {
            setIsProcessing(false);
        }
    }, [_onTranscript, onResponseText, playPcmAudio, stopAudioPlayback]);

    const handleMessage = useCallback((event: MessageEvent) => {
        if (typeof event.data === 'string') {
            try {
                handleParsedMessage(parseLiveMessage(event.data));
            } catch (caught) {
                setError(toFriendlyVoiceError(caught instanceof Error ? caught.message : undefined));
                setIsProcessing(false);
            }
            return;
        }

        if (event.data instanceof Blob) {
            const reader = new FileReader();
            reader.onload = () => {
                try {
                    handleParsedMessage(parseLiveMessage(reader.result));
                } catch (caught) {
                    setError(toFriendlyVoiceError(caught instanceof Error ? caught.message : undefined));
                    setIsProcessing(false);
                }
            };
            reader.onerror = () => {
                setError('Nao consegui ler a resposta do canal de voz.');
                setIsProcessing(false);
            };
            reader.readAsText(event.data);
            return;
        }

        setError('Evento de voz em formato inesperado.');
        setIsProcessing(false);
    }, [handleParsedMessage]);

    const startSession = useCallback(async (override?: { token?: string; model?: string; voiceName?: string }) => {
        if (setupCompleteRef.current || wsRef.current?.readyState === WebSocket.CONNECTING) return;
        const liveToken = override?.token || token;
        const liveModel = override?.model || model;
        const liveVoiceName = override?.voiceName || voiceName;

        if (!liveToken) {
            setError('Token de voz indisponivel.');
            return;
        }

        try {
            manualCloseRef.current = false;
            setupCompleteRef.current = false;
            setError(null);
            setLastResponse('');
            setIsProcessing(true);

            audioContextRef.current = new AudioContext({ sampleRate: 16000 });

            try {
                await audioContextRef.current.audioWorklet.addModule('/worklets/gemini-voice-processor.js');
            } catch {
                const workletBlob = new Blob([AUDIO_WORKLET_CODE], { type: 'application/javascript' });
                const workletUrl = URL.createObjectURL(workletBlob);
                await audioContextRef.current.audioWorklet.addModule(workletUrl);
                URL.revokeObjectURL(workletUrl);
            }

            streamRef.current = await navigator.mediaDevices.getUserMedia({
                audio: {
                    channelCount: 1,
                    sampleRate: 16000,
                    echoCancellation: true,
                    noiseSuppression: true,
                    autoGainControl: true,
                },
            });

            const source = audioContextRef.current.createMediaStreamSource(streamRef.current);
            workletNodeRef.current = new AudioWorkletNode(audioContextRef.current, 'audio-processor');

            workletNodeRef.current.port.onmessage = (event) => {
                if (event.data.type === 'intensity') {
                    audioIntensityRef.current = event.data.value;
                    const now = Date.now();
                    if (now - lastIntensityUpdateRef.current > 100) {
                        setAudioIntensity(event.data.value);
                        lastIntensityUpdateRef.current = now;
                    }
                    onAudioIntensity?.(event.data.value);
                    return;
                }

                if (event.data.type === 'audio' && wsRef.current?.readyState === WebSocket.OPEN && isListeningRef.current) {
                    const base64Audio = uint8ToBase64(new Uint8Array(event.data.data));
                    wsRef.current.send(JSON.stringify({
                        realtimeInput: {
                            audio: {
                                mimeType: 'audio/pcm;rate=16000',
                                data: base64Audio,
                            },
                        },
                    }));
                }
            };

            source.connect(workletNodeRef.current);
            silenceNodeRef.current = audioContextRef.current.createGain();
            silenceNodeRef.current.gain.value = 0;
            workletNodeRef.current.connect(silenceNodeRef.current);
            silenceNodeRef.current.connect(audioContextRef.current.destination);

            const wsUrl = `wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1alpha.GenerativeService.BidiGenerateContentConstrained?access_token=${encodeURIComponent(liveToken)}`;
            wsRef.current = new WebSocket(wsUrl);

            wsRef.current.onopen = () => {
                wsRef.current?.send(JSON.stringify({
                    setup: {
                        model: `models/${liveModel}`,
                        responseModalities: ['AUDIO'],
                        temperature: 0.5,
                        speechConfig: {
                            voiceConfig: {
                                prebuiltVoiceConfig: {
                                    voiceName: liveVoiceName,
                                },
                            },
                        },
                        systemInstruction: {
                            parts: [{ text: systemInstruction }],
                        },
                        inputAudioTranscription: {},
                        outputAudioTranscription: {},
                    },
                }));
            };

            wsRef.current.onmessage = handleMessage;

            wsRef.current.onerror = () => {
                setError('Falha ao conectar com o modo voz. Tente iniciar uma nova sessao.');
                setIsProcessing(false);
            };

            wsRef.current.onclose = () => {
                wsRef.current = null;
                const wasSetupComplete = setupCompleteRef.current;
                cleanupResources();
                if (!manualCloseRef.current && !wasSetupComplete) {
                    setError('A conexao de voz foi encerrada antes da confirmacao do Live API.');
                }
            };
        } catch (caught: unknown) {
            cleanupResources();
            setError(toFriendlyVoiceError(caught instanceof Error ? caught.message : undefined));
        }
    }, [cleanupResources, handleMessage, model, onAudioIntensity, systemInstruction, token, voiceName]);

    const endSession = useCallback(() => {
        manualCloseRef.current = true;
        if (wsRef.current) {
            wsRef.current.close();
            wsRef.current = null;
        }
        cleanupResources();
    }, [cleanupResources]);

    const toggleListening = useCallback(() => {
        if (!isConnected) {
            void startSession();
            return;
        }

        setIsListening((previous) => {
            const next = !previous;
            isListeningRef.current = next;
            return next;
        });
    }, [isConnected, startSession]);

    const sendTextMessage = useCallback((text: string) => {
        if (!wsRef.current || wsRef.current.readyState !== WebSocket.OPEN) return;

        setIsProcessing(true);
        setLastResponse('');

        wsRef.current.send(JSON.stringify({
            realtimeInput: {
                text,
            },
        }));
    }, []);

    useEffect(() => () => {
        manualCloseRef.current = true;
        cleanupResources();
        wsRef.current?.close();
        wsRef.current = null;
    }, [cleanupResources]);

    return {
        isConnected,
        isSpeaking,
        isListening,
        isProcessing,
        audioIntensity,
        getAudioVolume: useCallback(() => audioIntensityRef.current, []),
        transcript,
        lastResponse,
        startSession,
        endSession,
        toggleListening,
        sendTextMessage,
        error,
    };
}
