import { useState, useRef, useCallback, useEffect } from 'react';
import { GeminiLiveClient, GeminiLiveStatus } from '@/lib/gemini-live-client';

interface UseGeminiLiveOptions {
    onConnect?: () => void;
    onDisconnect?: () => void;
    onError?: (error: string) => void;
}

export function useGeminiLive(options?: UseGeminiLiveOptions) {
    const [status, setStatus] = useState<GeminiLiveStatus>('disconnected');
    const [isSpeaking, setIsSpeaking] = useState<boolean>(false);
    
    const clientRef = useRef<GeminiLiveClient | null>(null);
    const volumeRef = useRef<number>(0);
    const apiKey = "AIzaSyAFcPfN4qK8cDfPNoEKGYIqzXdC7l5B0YI"; // Voice exclusive key

    const startSession = useCallback(async ({ clientTools }: { clientTools?: Record<string, Function> }) => {
        if (clientRef.current?.getStatus() === 'connected') return;

        // Load pre-built tool schema generated by parse-tools.cjs
        let toolDeclarations: any[] = [];
        try {
            const mod = await import('@/lib/gemini-voice-tools.json');
            toolDeclarations = mod.default || mod;
        } catch(e) {
            console.warn("Tools declaradas localmente não encontradas, prosseguindo sem.");
        }

        const client = new GeminiLiveClient({
            apiKey,
            systemInstruction: "Você é o Synapse, a IA médica avançada do sistema NeuroNex Desktop. Fale num tom caloroso, eficiente e profissional. Auxilie o usuário em ações clínicas, seja concisa.",
            tools: toolDeclarations.length ? toolDeclarations : undefined,
            onStatusChange: (newStatus) => {
                setStatus(newStatus);
                if (newStatus === 'connected') options?.onConnect?.();
                if (newStatus === 'disconnected') options?.onDisconnect?.();
            },
            onSpeechStatusChange: setIsSpeaking,
            onVolumeChange: (vol) => { volumeRef.current = vol; },
            onToolCall: async (name, params) => {
                if (clientTools && clientTools[name]) {
                    const res = await clientTools[name](params);
                    return res;
                }
                return { error: `Tool ${name} handler not found in client` };
            },
            onError: (err) => {
                options?.onError?.(err.message);
            }
        });
        
        clientRef.current = client;
        await client.connect();
    }, [apiKey, options]);

    const endSession = useCallback(async () => {
        if (clientRef.current) {
            clientRef.current.disconnect();
            clientRef.current = null;
        }
    }, []);

    const getInputVolume = useCallback(() => {
        return volumeRef.current;
    }, []);

    // Cleanup on unmount
    useEffect(() => {
        return () => {
            if (clientRef.current) {
                clientRef.current.disconnect();
            }
        };
    }, []);

    return {
        status,
        isSpeaking,
        getInputVolume,
        startSession,
        endSession
    };
}
