// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://krewdaklcyzqfxkkgvqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZXdkYWtsY3l6cWZ4a2tndnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NjA3NDMsImV4cCI6MjA3NzQzNjc0M30.4UF003hI4Cn5denbdsSFPgYiacS_RGNkRQP_9JSOpbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);